
package com.slscomm.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import javax.xml.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommHandlerImplService", targetNamespace = "http://ws.slscomm.com/", wsdlLocation = "http://elcloudo.tamu.edu:8080/SLSComm/commhandler?wsdl")
public class CommHandlerImplService
    extends Service
{

    private final static URL COMMHANDLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMHANDLERIMPLSERVICE_EXCEPTION;
    private final static QName COMMHANDLERIMPLSERVICE_QNAME = new QName("http://ws.slscomm.com/", "CommHandlerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://elcloudo.tamu.edu:8080/SLSComm/commhandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMHANDLERIMPLSERVICE_WSDL_LOCATION = url;
        COMMHANDLERIMPLSERVICE_EXCEPTION = e;
    }

    public CommHandlerImplService() {
        super(__getWsdlLocation(), COMMHANDLERIMPLSERVICE_QNAME);
    }

    public CommHandlerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMHANDLERIMPLSERVICE_QNAME, features);
    }

    public CommHandlerImplService(URL wsdlLocation) {
        super(wsdlLocation, COMMHANDLERIMPLSERVICE_QNAME);
    }

    public CommHandlerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMHANDLERIMPLSERVICE_QNAME, features);
    }

    public CommHandlerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommHandlerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommHandler
     */
    @WebEndpoint(name = "CommHandlerImplPort")
    public CommHandler getCommHandlerImplPort() {
        return super.getPort(new QName("http://ws.slscomm.com/", "CommHandlerImplPort"), CommHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommHandler
     */
    @WebEndpoint(name = "CommHandlerImplPort")
    public CommHandler getCommHandlerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.slscomm.com/", "CommHandlerImplPort"), CommHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMHANDLERIMPLSERVICE_EXCEPTION!= null) {
            throw COMMHANDLERIMPLSERVICE_EXCEPTION;
        }
        return COMMHANDLERIMPLSERVICE_WSDL_LOCATION;
    }

}
